### PR TITLE
feat(plugin): add branch to the generated url

### PR DESCRIPTION
**Pull request by dudyn5ky1**
Hello @izifortune ,

I really like this plugin, very good job!

Sometimes I want to generate an url for the branch that was not yet merged to master. This PR introduces such functionality. 

Cheers!

### CODE REVIEW

**Comment by izifortune** [comment]
Thanks Maksym that looks great. One small comment on my side, I'm often in branches that are not pushed to the origin yet.
Is there a way have the branches optional?

**Comment by dudyn5ky1** [comment]
@izifortune good point. 

Do you want to have it as a separate command, like `:WebLinkBranch`?

**Comment by izifortune** [comment]
I think that will work!

**Comment by dudyn5ky1** [comment]
@izifortune done.

**Review by izifortune — APPROVED** [review]

**Pull request merged**
